-- ============================================================================
-- ESQUEMA BASE de SIM WEB — solo ESTRUCTURA, cero datos
-- ----------------------------------------------------------------------------
-- Por qué existe: los 63 archivos de db/ son INCREMENTALES y crean 59 tablas
-- (ia_*, mensualidad_*, cronograma_*, sim_control_*, campeonato_checkouts,
-- y las de configuración comercial posteriores). Las 47 tablas
-- de negocio originales —reservas, turnos_stand, campeonatos, gift_cards, todo
-- fin_*, colectivo_*, empresa_*, los brackets— se crearon fuera del repositorio al
-- principio del proyecto y existían SOLO en Producción. Sin ellas no se puede
-- levantar una base de pruebas, y por eso las 53 suites mutantes solo podían correr
-- contra la base real.
--
-- Cómo se obtuvo: introspección de SOLO LECTURA del catálogo de Producción
-- (pg_catalog / information_schema). NO es un dump de datos: no contiene una sola
-- fila, ni clientes, ni teléfonos, ni correos, ni pagos.
--
-- Orden del archivo (importante en una base vacía):
--   1. extensiones      2. tablas sin constraints
--   3. claves primarias, únicas y checks                4. claves foráneas
--   5. índices          6. row level security
--
-- Destino: la base LOCAL de pruebas. Aplicarlo a Producción sería un no-op
-- (todo es `if not exists` / aditivo), pero no es su propósito.
-- ============================================================================

-- ── 1. Extensiones ─────────────────────────────────────────────────────────
create extension if not exists pgcrypto;
create extension if not exists "uuid-ossp";
create extension if not exists btree_gist;

-- ── 1b. Tipos propios ───────────────────────────────────────────────────────
-- cronograma_timerange es un rango sobre `time`. Crearlo da automáticamente sus
-- constructores (cronograma_timerange(...), cronograma_timemultirange(...)), que en
-- Producción aparecen como funciones del esquema public pero no se escriben a mano.
do $$
begin
  if not exists (select 1 from pg_type t join pg_namespace n on n.oid=t.typnamespace
                 where n.nspname='public' and t.typname='cronograma_timerange') then
    create type public.cronograma_timerange as range (subtype = time without time zone);
  end if;
end $$;

-- ── 2a. Tablas: reservas, turnero, gift cards, códigos, empresas, colectivo ──
create sequence if not exists public.turnos_historicos_id_seq;

create table if not exists public.bloqueos_reservas (
  id bigint generated always as identity not null,
  fecha date not null,
  todo_el_dia boolean default true not null,
  hora_inicio text,
  hora_fin text,
  simulador text,
  motivo text,
  activo boolean default true not null,
  created_at timestamp with time zone default now() not null
);

create table if not exists public.codigos_descuento (
  id bigint generated by default as identity not null,
  codigo text not null,
  descripcion text,
  tipo_descuento text default 'porcentaje'::text not null,
  valor_descuento numeric not null,
  usos_maximos integer,
  usos_actuales integer default 0 not null,
  fecha_inicio date,
  fecha_fin date,
  activo boolean default true not null,
  creado_para text,
  created_at timestamp with time zone default now() not null,
  deleted_at timestamp with time zone,
  solo_dias_habiles boolean default false not null,
  dias_permitidos integer[],
  fechas_bloqueadas date[],
  duraciones_permitidas integer[]
);

create table if not exists public.colectivo_eventos (
  id uuid default gen_random_uuid() not null,
  nombre text not null,
  fecha_inicio date not null,
  fecha_fin date not null,
  hora_inicio text,
  hora_fin text,
  localidad text,
  provincia text,
  ubicacion text,
  organizador text,
  telefono_contacto text,
  observaciones text,
  estado text default 'proximo'::text not null,
  created_by text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  finalizado_at timestamp with time zone
);

create table if not exists public.colectivo_productos (
  id uuid default gen_random_uuid() not null,
  nombre text not null,
  precio_predeterminado numeric default 0 not null,
  activo boolean default true not null,
  orden integer default 0 not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table if not exists public.colectivo_turnos (
  id bigint generated always as identity not null,
  evento_id uuid not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  created_by text,
  nombre text,
  telefono text,
  fecha date not null,
  hora text,
  hora_estimada_subida text,
  hora_subida text,
  hora_bajada text,
  simuladores jsonb default '[]'::jsonb not null,
  cantidad_simuladores integer default 0 not null,
  cantidad_personas integer default 1 not null,
  cantidad_minutos integer default 10 not null,
  cantidad_turnos integer default 1 not null,
  metodo_pago text default 'efectivo'::text,
  posnet_pago text,
  pagos_detalle jsonb default '[]'::jsonb not null,
  turno_listo boolean default false not null,
  total numeric default 0 not null,
  estado text default 'activo'::text not null,
  observaciones text
);

create table if not exists public.colectivo_ventas (
  id uuid default gen_random_uuid() not null,
  evento_id uuid not null,
  producto_id uuid,
  producto_nombre text,
  fecha date not null,
  fecha_hora timestamp with time zone default now() not null,
  cantidad integer default 1 not null,
  precio_unitario numeric default 0 not null,
  total numeric default 0 not null,
  cliente text,
  telefono text,
  observaciones text,
  metodo_pago text,
  posnet_pago text,
  pagos_detalle jsonb default '[]'::jsonb not null,
  estado text default 'activa'::text not null,
  created_by text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table if not exists public.empresa_campanias (
  id uuid default gen_random_uuid() not null,
  empresa text not null,
  nombre_campania text,
  contacto_nombre text,
  contacto_telefono text,
  contacto_email text,
  cuit text,
  modalidad text default 'unica'::text not null,
  cantidad_contratada integer default 0 not null,
  duracion_minutos integer default 15 not null,
  usos_por_codigo integer default 1 not null,
  precio_neto numeric default 0 not null,
  iva_porcentaje numeric default 21 not null,
  precio_total numeric generated always as (round((precio_neto * ((1)::numeric + (iva_porcentaje / (100)::numeric))), 2)) stored,
  fecha_pago date,
  estado_pago text default 'pendiente'::text not null,
  fecha_inicio date,
  fecha_vencimiento date,
  estado text default 'borrador'::text not null,
  observaciones text,
  codigos_generados boolean default false not null,
  ultimo_informe_at timestamp with time zone,
  informe_definitivo_at timestamp with time zone,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  created_by text,
  deleted_at timestamp with time zone,
  deleted_by text,
  medio_pago text,
  modalidad_comercial text
);

create table if not exists public.empresa_codigo_usos (
  id uuid default gen_random_uuid() not null,
  codigo_id uuid not null,
  campania_id uuid not null,
  beneficiario_nombre text,
  beneficiario_apellido text,
  beneficiario_telefono text,
  beneficiario_email text,
  reserva_id bigint,
  estado text default 'consumido'::text not null,
  created_at timestamp with time zone default now() not null,
  idempotency_key text
);

create table if not exists public.empresa_codigos (
  id uuid default gen_random_uuid() not null,
  campania_id uuid not null,
  codigo text not null,
  estado text default 'disponible'::text not null,
  usos_maximos integer default 1 not null,
  usos_actuales integer default 0 not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table if not exists public.gift_card_logs (
  id uuid default gen_random_uuid() not null,
  gift_card_id uuid not null,
  accion text not null,
  rol text,
  detalle jsonb default '{}'::jsonb not null,
  created_at timestamp with time zone default now() not null
);

create table if not exists public.gift_cards (
  id uuid default gen_random_uuid() not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  codigo_unico text not null,
  comprador_nombre text not null,
  comprador_telefono text not null,
  destinatario_nombre text,
  duracion_minutos integer not null,
  monto numeric not null,
  estado_pago text default 'pendiente_pago'::text not null,
  estado_uso text default 'pendiente'::text not null,
  mercado_pago_payment_id text,
  mercado_pago_preference_id text,
  fecha_pago timestamp with time zone,
  fecha_uso timestamp with time zone,
  observaciones text,
  codigo_descuento text,
  monto_original numeric,
  descuento_aplicado numeric default 0,
  cantidad integer default 1 not null,
  modo_uso text default 'separadas'::text not null,
  grupo_compra_id uuid,
  usos_totales integer default 1 not null,
  usos_disponibles integer default 1 not null,
  fecha_vencimiento timestamp with time zone,
  deleted_at timestamp with time zone,
  deleted_by text,
  canal text default 'web'::text not null,
  medio_pago text,
  procesador text,
  registrado_por text
);

create table if not exists public.pendientes (
  id bigint generated by default as identity not null,
  descripcion text,
  fecha_limite date,
  completado boolean default false not null,
  completado_at timestamp with time zone,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  titulo text not null
);

create table if not exists public.reserva_operacion (
  reserva_id bigint not null,
  hora_subida text,
  hora_bajada text,
  listo boolean default false not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table if not exists public.reserva_slots (
  id bigint generated always as identity not null,
  reserva_id bigint not null,
  fecha text not null,
  hora text not null,
  simulador text not null,
  estado text default 'activa'::text not null,
  created_at timestamp with time zone default now() not null,
  ocupacion_min integer
);

create table if not exists public.reservas (
  id bigint generated always as identity not null,
  created_at timestamp with time zone default now(),
  nombre text not null,
  telefono text not null,
  fecha text not null,
  hora text not null,
  simuladores jsonb not null,
  cantidad_turnos integer not null,
  total numeric not null,
  estado text default 'activa'::text not null,
  acepto_condiciones boolean default false not null,
  mercado_pago_payment_id text,
  codigo_descuento text,
  descuento_aplicado numeric default 0,
  total_original numeric,
  duracion_minutos integer default 15 not null,
  apellido text,
  email text,
  origen text default 'web'::text not null,
  empresa_campania_id uuid,
  empresa_codigo_id uuid,
  no_show boolean default false not null,
  mensualidad_id uuid,
  minutos_consumidos integer,
  importe_complementario numeric default 0 not null,
  cobertura text,
  idempotency_key text,
  condiciones_version text,
  condiciones_at timestamp with time zone,
  referencia_publica text,
  cancelada_at timestamp with time zone,
  cancelacion_resultado text,
  reprogramada_at timestamp with time zone,
  reprogramaciones integer default 0 not null,
  modalidad text
);

create table if not exists public.reservas_precios_especiales (
  id uuid default gen_random_uuid() not null,
  fecha date not null,
  precio_15 integer,
  precio_30 integer,
  created_by text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  precio_10 integer,
  precio_20 integer
);

create table if not exists public.sorteos (
  id uuid default gen_random_uuid() not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  titulo text not null,
  descripcion text,
  premio text not null,
  estado text default 'proximo'::text not null,
  fecha_inicio date,
  fecha_fin date,
  condiciones text,
  imagen_url text,
  deleted_at timestamp with time zone,
  deleted_by text
);

create table if not exists public.turnos_historicos (
  id bigint default nextval('turnos_historicos_id_seq'::regclass) not null,
  created_at timestamp with time zone default now(),
  archivo_nombre text not null,
  archivo_key text not null,
  fecha text not null,
  hora_subida text,
  hora_bajada text,
  hora_tomado text,
  metodo_pago text not null,
  total numeric default 0,
  cantidad_simuladores integer default 1,
  cantidad_turnos integer default 1,
  duracion integer default 15,
  escuderia text,
  hash_unico text not null,
  origen text default 'excel'::text
);
alter sequence public.turnos_historicos_id_seq owned by public.turnos_historicos.id;

create table if not exists public.turnos_stand (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now(),
  nombre text,
  telefono text,
  fecha date not null,
  hora text not null,
  simuladores jsonb,
  cantidad_simuladores integer,
  cantidad_turnos integer default 1,
  duracion_minutos integer default 20,
  total numeric default 0,
  metodo_pago text default 'efectivo'::text,
  estado text default 'activo'::text,
  observaciones text,
  hora_estimada_subida text,
  hora_subida text,
  cantidad_personas integer default 1,
  cantidad_minutos integer default 15,
  hora_bajada text,
  posnet_pago text,
  pagos_detalle jsonb default '[]'::jsonb,
  turno_listo boolean default false not null,
  modalidad text
);

create table if not exists public.usos_codigos_descuento (
  id bigint generated by default as identity not null,
  codigo_id bigint,
  codigo text not null,
  reserva_id bigint,
  nombre text,
  telefono text,
  fecha_reserva date,
  hora_reserva text,
  total_original numeric,
  descuento_aplicado numeric,
  total_final numeric,
  mercado_pago_payment_id text,
  created_at timestamp with time zone default now() not null
);

-- ── 2b. Tablas: campeonatos y brackets ──────────────────────────────────────
create table if not exists public.campeonatos (
  id uuid default gen_random_uuid() not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  nombre text not null,
  descripcion text,
  estado text default 'proximo'::text not null,
  fecha_inicio date,
  fecha_fin date,
  precio_inscripcion numeric(12,2) default 0 not null,
  cupos_maximos integer default 0 not null,
  inscripcion_habilitada boolean default true not null,
  categorias text[] default ARRAY['oro'::text, 'plata'::text, 'bronce'::text] not null,
  imagen_url text,
  deleted_at timestamp with time zone,
  deleted_by text,
  modalidad text default 'liga'::text not null,
  permite_pago_stand boolean default true not null,
  usa_ronda_preliminar boolean default false not null,
  config jsonb default '{}'::jsonb not null
);

create table if not exists public.campeonato_fechas (
  id uuid default gen_random_uuid() not null,
  created_at timestamp with time zone default now() not null,
  campeonato_id uuid not null,
  numero_fecha integer not null,
  nombre text,
  circuito text,
  fecha_evento date,
  estado text default 'abierta'::text,
  fecha_inicio date,
  fecha_fin date,
  cerrado_at timestamp with time zone,
  cerrado_por text,
  observaciones text
);

create table if not exists public.campeonato_inscripciones (
  id uuid default gen_random_uuid() not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  campeonato_id uuid,
  nombre text not null,
  apellido text not null,
  nombre_completo text not null,
  telefono text not null,
  dni text not null,
  instagram text,
  escuderia_favorita text,
  categoria text,
  monto numeric(12,2) default 0 not null,
  estado_pago text default 'pendiente_pago'::text not null,
  payment_id text,
  preference_id text,
  observaciones text,
  metodo_pago text,
  eliminada_at timestamp with time zone,
  categoria_manual boolean default false not null,
  hora_toma text,
  hora_subida text,
  hora_bajada text,
  cantidad_minutos integer,
  hora_estimada_subida text,
  pagos_detalle jsonb
);

create table if not exists public.campeonato_registros (
  id uuid default gen_random_uuid() not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  fecha date not null,
  hora time without time zone,
  nombre text not null,
  apellido text,
  nombre_completo text not null,
  telefono text,
  categoria text not null,
  campeonato_id uuid,
  campeonato_fecha_id uuid,
  circuito text,
  tiempo text,
  tiempo_segundos numeric(12,4) default 999999 not null,
  simulador text,
  puntos integer default 0 not null,
  semana integer default 1 not null,
  escuderia_favorita text,
  observaciones text,
  estado text default 'valido'::text,
  hora_estimada_subida time without time zone,
  hora_subida time without time zone,
  hora_bajada time without time zone,
  cantidad_minutos integer default 15,
  cantidad_turnos integer default 1,
  turno_listo boolean default false,
  pagos_detalle jsonb,
  total numeric(12,2) default 0,
  inscripcion_id uuid,
  tiempo_crudo_ms integer,
  penalizacion_ms integer default 0 not null,
  tiempo_oficial_ms integer generated always as (
CASE
    WHEN (tiempo_crudo_ms IS NULL) THEN NULL::integer
    ELSE (tiempo_crudo_ms + COALESCE(penalizacion_ms, 0))
END) stored
);

create table if not exists public.campeonato_penalizaciones (
  id uuid default gen_random_uuid() not null,
  campeonato_id uuid not null,
  categoria text not null,
  fecha_origen_id uuid not null,
  fecha_destino_id uuid not null,
  inscripcion_id uuid,
  piloto_key text not null,
  piloto_nombre text,
  posicion integer not null,
  penalizacion_ms integer not null,
  created_at timestamp with time zone default now() not null
);

create table if not exists public.campeonato_bracket (
  id uuid default gen_random_uuid() not null,
  campeonato_id uuid not null,
  estado text default 'clasificacion'::text not null,
  seeding_modo text default 'clasificacion'::text not null,
  clasificacion_habilitada boolean default true not null,
  config_snapshot jsonb default '{}'::jsonb not null,
  podio jsonb,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  cerrada_at timestamp with time zone,
  generado_at timestamp with time zone,
  finalizado_at timestamp with time zone
);

create table if not exists public.campeonato_bracket_participantes (
  id uuid default gen_random_uuid() not null,
  bracket_id uuid not null,
  inscripcion_id uuid not null,
  presente boolean default true not null,
  incluido boolean default true not null,
  estado text default 'activo'::text not null,
  mejor_ms integer,
  seed integer,
  orden_inscripcion integer default 0 not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table if not exists public.campeonato_bracket_rondas (
  id uuid default gen_random_uuid() not null,
  bracket_id uuid not null,
  numero integer not null,
  nombre text,
  tipo text default 'principal'::text not null,
  estado text default 'pendiente'::text not null,
  created_at timestamp with time zone default now() not null,
  started_at timestamp with time zone,
  finished_at timestamp with time zone
);

create table if not exists public.campeonato_bracket_carreras (
  id uuid default gen_random_uuid() not null,
  bracket_id uuid not null,
  ronda_id uuid not null,
  numero integer not null,
  estado text default 'pendiente'::text not null,
  es_bye boolean default false not null,
  vueltas integer default 0 not null,
  created_at timestamp with time zone default now() not null,
  started_at timestamp with time zone,
  finished_at timestamp with time zone
);

create table if not exists public.campeonato_bracket_carrera_participantes (
  id uuid default gen_random_uuid() not null,
  bracket_id uuid not null,
  ronda_id uuid not null,
  carrera_id uuid not null,
  inscripcion_id uuid not null,
  seed integer,
  origen_carrera_id uuid,
  origen_posicion integer,
  posicion_final integer,
  estado text default 'activo'::text not null,
  clasifica boolean,
  observacion text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

-- ── 2c. Tablas: Finanzas ────────────────────────────────────────────────────
create table if not exists public.fin_cuentas (
  id uuid default gen_random_uuid() not null,
  nombre text not null,
  ambito text not null,
  tipo text not null,
  activa boolean default true not null,
  orden integer default 0 not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table if not exists public.fin_categorias (
  id uuid default gen_random_uuid() not null,
  nombre text not null,
  ambito text not null,
  tipo text not null,
  activa boolean default true not null,
  orden integer default 0 not null,
  color text,
  descripcion text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  protegida boolean default false not null
);

create table if not exists public.fin_movimientos (
  id uuid default gen_random_uuid() not null,
  fecha date not null,
  mes_contable text not null,
  ambito text not null,
  tipo text not null,
  clasificacion text not null,
  cuenta_origen_id uuid,
  cuenta_destino_id uuid,
  categoria_id uuid,
  subcategoria text,
  descripcion text default ''::text not null,
  monto numeric not null,
  observaciones text,
  origen text default 'manual'::text not null,
  referencia_externa text,
  creado_por text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table if not exists public.fin_reglas_clasificacion (
  id uuid default gen_random_uuid() not null,
  ambito text,
  keyword text not null,
  tipo_sugerido text,
  clasificacion_sugerida text,
  categoria_id uuid,
  cuenta_id uuid,
  prioridad integer default 100 not null,
  activa boolean default true not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table if not exists public.fin_clasificacion_ingresos (
  id uuid default gen_random_uuid() not null,
  fuente text not null,
  categoria_id uuid,
  activa boolean default true not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table if not exists public.fin_cierres_mensuales (
  id uuid default gen_random_uuid() not null,
  mes text not null,
  estado text default 'abierto'::text not null,
  observaciones text,
  cerrado_at timestamp with time zone,
  cerrado_por text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  saldo_inicial_general numeric default 0 not null,
  saldo_teorico_general numeric default 0 not null,
  saldo_real_general numeric default 0 not null,
  diferencia_general numeric default 0 not null,
  saldo_inicial_efectivo numeric default 0 not null,
  saldo_inicial_mp numeric default 0 not null,
  saldo_teorico_efectivo numeric default 0 not null,
  saldo_teorico_mp numeric default 0 not null,
  saldo_real_efectivo numeric default 0 not null,
  saldo_real_mp numeric default 0 not null,
  diferencia_efectivo numeric default 0 not null,
  diferencia_mp numeric default 0 not null,
  informe_generado_at timestamp with time zone
);

create table if not exists public.fin_cierres_cuentas (
  id uuid default gen_random_uuid() not null,
  cierre_id uuid not null,
  cuenta_id uuid not null,
  saldo_inicial numeric default 0 not null,
  saldo_teorico numeric default 0 not null,
  saldo_real numeric default 0 not null,
  diferencia numeric default 0 not null
);

create table if not exists public.fin_configuracion (
  id integer default 1 not null,
  cantidad_simuladores integer default 4 not null,
  horas_operativas_dia numeric default 12 not null,
  duracion_turno_min integer default 15 not null,
  dias_operativos_mes integer default 30 not null,
  valor_activos numeric default 0 not null,
  inversion_inicial numeric default 0 not null,
  meta_facturacion numeric default 0 not null,
  meta_margen_operativo numeric default 0 not null,
  meta_ocupacion numeric default 0 not null,
  updated_at timestamp with time zone default now() not null,
  mes_inicio text default '2026-07'::text not null
);

create table if not exists public.fin_logs (
  id bigint generated always as identity not null,
  accion text not null,
  entidad text not null,
  entidad_id text,
  detalle jsonb,
  rol text,
  created_at timestamp with time zone default now() not null
);

create table if not exists public.fin_sueldos (
  id uuid default gen_random_uuid() not null,
  mes text not null,
  monto numeric default 0 not null,
  observacion text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table if not exists public.fin_saldos_iniciales (
  id uuid default gen_random_uuid() not null,
  mes text not null,
  monto numeric default 0 not null,
  observacion text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  monto_efectivo numeric default 0 not null,
  monto_mercado_pago numeric default 0 not null
);

create table if not exists public.fin_excepciones_operativas (
  id uuid default gen_random_uuid() not null,
  fecha date not null,
  cerrado boolean default false not null,
  horas numeric,
  simuladores integer,
  motivo text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table if not exists public.fin_recurrencias (
  id uuid default gen_random_uuid() not null,
  frecuencia text not null,
  fecha_inicio date not null,
  fecha_fin date,
  cantidad_repeticiones integer,
  tipo text not null,
  monto numeric not null,
  descripcion text default ''::text not null,
  categoria_id uuid,
  cuenta_estimada text default 'mercado_pago'::text not null,
  probabilidad integer default 100 not null,
  proveedor_cliente text,
  observaciones text,
  activa boolean default true not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table if not exists public.fin_deudas (
  id uuid default gen_random_uuid() not null,
  descripcion text not null,
  proveedor text,
  monto_total numeric not null,
  cuotas_total integer default 1 not null,
  estado text default 'activa'::text not null,
  observaciones text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  es_prestamo boolean default false not null,
  acreedor text,
  monto_recibido numeric,
  cuenta_destino text,
  movimiento_financiamiento_id uuid
);

create table if not exists public.fin_eventos_futuros (
  id uuid default gen_random_uuid() not null,
  fecha date not null,
  mes_contable text not null,
  tipo text not null,
  estado text default 'pendiente'::text not null,
  descripcion text default ''::text not null,
  categoria_id uuid,
  monto numeric not null,
  cuenta_estimada text default 'mercado_pago'::text not null,
  probabilidad integer default 100 not null,
  proveedor_cliente text,
  observaciones text,
  es_recurrente boolean default false not null,
  recurrencia_id uuid,
  deuda_id uuid,
  cuota_numero integer,
  movimiento_id uuid,
  fecha_real date,
  editado_manual boolean default false not null,
  creado_por text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table if not exists public.fin_whatsapp_pendientes (
  id uuid default gen_random_uuid() not null,
  phone text not null,
  message_id text,
  texto_original text not null,
  interpretacion_json jsonb,
  estado text default 'pendiente'::text not null,
  resultado_id uuid,
  expires_at timestamp with time zone default (now() + '00:30:00'::interval) not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table if not exists public.fin_comisiones_cobro (
  id uuid default gen_random_uuid() not null,
  procesador text not null,
  metodo_pago text not null,
  porcentaje_base numeric default 0 not null,
  aplica_iva boolean default true not null,
  iva_porcentaje numeric default 21 not null,
  acreditacion text default 'inmediata'::text not null,
  activa boolean default true not null,
  fecha_desde date,
  fecha_hasta date,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

-- ── 3. Claves primarias, únicas y checks ───────────────────────────────────
alter table public.bloqueos_reservas add constraint bloqueos_reservas_pkey PRIMARY KEY (id);
alter table public.campeonato_bracket add constraint campeonato_bracket_pkey PRIMARY KEY (id);
alter table public.campeonato_bracket_carrera_participantes add constraint campeonato_bracket_carrera_participantes_pkey PRIMARY KEY (id);
alter table public.campeonato_bracket_carreras add constraint campeonato_bracket_carreras_pkey PRIMARY KEY (id);
alter table public.campeonato_bracket_participantes add constraint campeonato_bracket_participantes_pkey PRIMARY KEY (id);
alter table public.campeonato_bracket_rondas add constraint campeonato_bracket_rondas_pkey PRIMARY KEY (id);
alter table public.campeonato_fechas add constraint campeonato_fechas_pkey PRIMARY KEY (id);
alter table public.campeonato_inscripciones add constraint campeonato_inscripciones_pkey PRIMARY KEY (id);
alter table public.campeonato_penalizaciones add constraint campeonato_penalizaciones_pkey PRIMARY KEY (id);
alter table public.campeonato_registros add constraint campeonato_registros_pkey PRIMARY KEY (id);
alter table public.campeonatos add constraint campeonatos_pkey PRIMARY KEY (id);
alter table public.codigos_descuento add constraint codigos_descuento_pkey PRIMARY KEY (id);
alter table public.colectivo_eventos add constraint colectivo_eventos_pkey PRIMARY KEY (id);
alter table public.colectivo_productos add constraint colectivo_productos_pkey PRIMARY KEY (id);
alter table public.colectivo_turnos add constraint colectivo_turnos_pkey PRIMARY KEY (id);
alter table public.colectivo_ventas add constraint colectivo_ventas_pkey PRIMARY KEY (id);
alter table public.empresa_campanias add constraint empresa_campanias_pkey PRIMARY KEY (id);
alter table public.empresa_codigo_usos add constraint empresa_codigo_usos_pkey PRIMARY KEY (id);
alter table public.empresa_codigos add constraint empresa_codigos_pkey PRIMARY KEY (id);
alter table public.fin_categorias add constraint fin_categorias_pkey PRIMARY KEY (id);
alter table public.fin_cierres_cuentas add constraint fin_cierres_cuentas_pkey PRIMARY KEY (id);
alter table public.fin_cierres_mensuales add constraint fin_cierres_mensuales_pkey PRIMARY KEY (id);
alter table public.fin_clasificacion_ingresos add constraint fin_clasificacion_ingresos_pkey PRIMARY KEY (id);
alter table public.fin_comisiones_cobro add constraint fin_comisiones_cobro_pkey PRIMARY KEY (id);
alter table public.fin_configuracion add constraint fin_configuracion_pkey PRIMARY KEY (id);
alter table public.fin_cuentas add constraint fin_cuentas_pkey PRIMARY KEY (id);
alter table public.fin_deudas add constraint fin_deudas_pkey PRIMARY KEY (id);
alter table public.fin_eventos_futuros add constraint fin_eventos_futuros_pkey PRIMARY KEY (id);
alter table public.fin_excepciones_operativas add constraint fin_excepciones_operativas_pkey PRIMARY KEY (id);
alter table public.fin_logs add constraint fin_logs_pkey PRIMARY KEY (id);
alter table public.fin_movimientos add constraint fin_movimientos_pkey PRIMARY KEY (id);
alter table public.fin_recurrencias add constraint fin_recurrencias_pkey PRIMARY KEY (id);
alter table public.fin_reglas_clasificacion add constraint fin_reglas_clasificacion_pkey PRIMARY KEY (id);
alter table public.fin_saldos_iniciales add constraint fin_saldos_iniciales_pkey PRIMARY KEY (id);
alter table public.fin_sueldos add constraint fin_sueldos_pkey PRIMARY KEY (id);
alter table public.fin_whatsapp_pendientes add constraint fin_whatsapp_pendientes_pkey PRIMARY KEY (id);
alter table public.gift_card_logs add constraint gift_card_logs_pkey PRIMARY KEY (id);
alter table public.gift_cards add constraint gift_cards_pkey PRIMARY KEY (id);
alter table public.pendientes add constraint pendientes_pkey PRIMARY KEY (id);
alter table public.reserva_operacion add constraint reserva_operacion_pkey PRIMARY KEY (reserva_id);
alter table public.reserva_slots add constraint reserva_slots_pkey PRIMARY KEY (id);
alter table public.reservas add constraint reservas_pkey PRIMARY KEY (id);
alter table public.reservas_precios_especiales add constraint reservas_precios_especiales_pkey PRIMARY KEY (id);
alter table public.sorteos add constraint sorteos_pkey PRIMARY KEY (id);
alter table public.turnos_historicos add constraint turnos_historicos_pkey PRIMARY KEY (id);
alter table public.turnos_stand add constraint turnos_stand_pkey PRIMARY KEY (id);
alter table public.usos_codigos_descuento add constraint usos_codigos_descuento_pkey PRIMARY KEY (id);

alter table public.campeonato_bracket add constraint campeonato_bracket_campeonato_id_key UNIQUE (campeonato_id);
alter table public.campeonato_bracket_carrera_participantes add constraint campeonato_bracket_carrera_partic_carrera_id_inscripcion_id_key UNIQUE (carrera_id, inscripcion_id);
alter table public.campeonato_bracket_carrera_participantes add constraint campeonato_bracket_carrera_particip_ronda_id_inscripcion_id_key UNIQUE (ronda_id, inscripcion_id);
alter table public.campeonato_bracket_carreras add constraint campeonato_bracket_carreras_ronda_id_numero_key UNIQUE (ronda_id, numero);
alter table public.campeonato_bracket_participantes add constraint campeonato_bracket_participantes_bracket_id_inscripcion_id_key UNIQUE (bracket_id, inscripcion_id);
alter table public.campeonato_bracket_rondas add constraint campeonato_bracket_rondas_bracket_id_numero_key UNIQUE (bracket_id, numero);
alter table public.codigos_descuento add constraint codigos_descuento_codigo_key UNIQUE (codigo);
alter table public.colectivo_productos add constraint colectivo_productos_nombre_key UNIQUE (nombre);
alter table public.empresa_codigos add constraint empresa_codigos_codigo_key UNIQUE (codigo);
alter table public.fin_categorias add constraint fin_categorias_nombre_ambito_tipo_key UNIQUE (nombre, ambito, tipo);
alter table public.fin_cierres_cuentas add constraint fin_cierres_cuentas_cierre_id_cuenta_id_key UNIQUE (cierre_id, cuenta_id);
alter table public.fin_cierres_mensuales add constraint fin_cierres_mensuales_mes_key UNIQUE (mes);
alter table public.fin_clasificacion_ingresos add constraint fin_clasificacion_ingresos_fuente_key UNIQUE (fuente);
alter table public.fin_comisiones_cobro add constraint fin_comisiones_cobro_procesador_metodo_pago_key UNIQUE (procesador, metodo_pago);
alter table public.fin_cuentas add constraint fin_cuentas_nombre_key UNIQUE (nombre);
alter table public.fin_excepciones_operativas add constraint fin_excepciones_operativas_fecha_key UNIQUE (fecha);
alter table public.fin_saldos_iniciales add constraint fin_saldos_iniciales_mes_key UNIQUE (mes);
alter table public.fin_sueldos add constraint fin_sueldos_mes_key UNIQUE (mes);
alter table public.fin_whatsapp_pendientes add constraint fin_whatsapp_pendientes_message_id_key UNIQUE (message_id);
alter table public.gift_cards add constraint gift_cards_codigo_unico_key UNIQUE (codigo_unico);
alter table public.reservas add constraint reservas_mercado_pago_payment_id_key UNIQUE (mercado_pago_payment_id);
alter table public.reservas_precios_especiales add constraint reservas_precios_especiales_fecha_key UNIQUE (fecha);
alter table public.turnos_historicos add constraint turnos_historicos_hash_unico_key UNIQUE (hash_unico);

alter table public.campeonato_bracket add constraint campeonato_bracket_estado_check CHECK ((estado = ANY (ARRAY['clasificacion'::text, 'cerrada'::text, 'en_curso'::text, 'finalizado'::text])));
alter table public.campeonato_bracket add constraint campeonato_bracket_seeding_modo_check CHECK ((seeding_modo = ANY (ARRAY['clasificacion'::text, 'manual'::text, 'aleatorio'::text])));
alter table public.campeonato_bracket_carrera_participantes add constraint campeonato_bracket_carrera_participantes_estado_check CHECK ((estado = ANY (ARRAY['activo'::text, 'dnf'::text, 'dsq'::text])));
alter table public.campeonato_bracket_carreras add constraint campeonato_bracket_carreras_estado_check CHECK ((estado = ANY (ARRAY['pendiente'::text, 'en_curso'::text, 'finalizada'::text])));
alter table public.campeonato_bracket_participantes add constraint campeonato_bracket_participantes_estado_check CHECK ((estado = ANY (ARRAY['activo'::text, 'ausente'::text, 'excluido'::text])));
alter table public.campeonato_bracket_rondas add constraint campeonato_bracket_rondas_estado_check CHECK ((estado = ANY (ARRAY['pendiente'::text, 'lista'::text, 'en_curso'::text, 'finalizada'::text])));
alter table public.campeonato_bracket_rondas add constraint campeonato_bracket_rondas_tipo_check CHECK ((tipo = ANY (ARRAY['preliminar'::text, 'principal'::text, 'final'::text])));
alter table public.campeonato_fechas add constraint campeonato_fechas_estado_check CHECK ((estado = ANY (ARRAY['abierta'::text, 'cerrada'::text])));
alter table public.campeonato_inscripciones add constraint campeonato_inscripciones_categoria_check CHECK (((categoria IS NULL) OR (categoria = ANY (ARRAY['oro'::text, 'plata'::text, 'bronce'::text, 'sin_clasificar'::text]))));
alter table public.campeonato_inscripciones add constraint campeonato_inscripciones_estado_pago_check CHECK ((estado_pago = ANY (ARRAY['pendiente_pago'::text, 'pagado'::text, 'cancelado'::text, 'rechazado'::text, 'pendiente_pago_online'::text, 'pendiente_pago_stand'::text])));
alter table public.campeonato_penalizaciones add constraint campeonato_penalizaciones_posicion_check CHECK ((posicion = ANY (ARRAY[1, 2, 3])));
alter table public.campeonato_registros add constraint campeonato_registros_categoria_check CHECK ((categoria = ANY (ARRAY['oro'::text, 'plata'::text, 'bronce'::text, 'sin_clasificar'::text])));
alter table public.campeonato_registros add constraint campeonato_registros_estado_check CHECK ((estado = ANY (ARRAY['valido'::text, 'pendiente'::text, 'anulado'::text])));
alter table public.campeonatos add constraint campeonatos_estado_check CHECK ((estado = ANY (ARRAY['proximo'::text, 'activo'::text, 'finalizado'::text])));
alter table public.colectivo_eventos add constraint colectivo_eventos_estado_check CHECK ((estado = ANY (ARRAY['proximo'::text, 'activo'::text, 'finalizado'::text, 'cancelado'::text])));
alter table public.colectivo_eventos add constraint colectivo_eventos_fechas CHECK ((fecha_fin >= fecha_inicio));
alter table public.colectivo_productos add constraint colectivo_productos_precio_predeterminado_check CHECK ((precio_predeterminado >= (0)::numeric));
alter table public.colectivo_turnos add constraint colectivo_turnos_cantidad_minutos_check CHECK ((cantidad_minutos > 0));
alter table public.colectivo_turnos add constraint colectivo_turnos_cantidad_personas_check CHECK ((cantidad_personas > 0));
alter table public.colectivo_turnos add constraint colectivo_turnos_cantidad_turnos_check CHECK ((cantidad_turnos > 0));
alter table public.colectivo_turnos add constraint colectivo_turnos_estado_check CHECK ((estado = ANY (ARRAY['activo'::text, 'cancelado'::text])));
alter table public.colectivo_turnos add constraint colectivo_turnos_total_check CHECK ((total >= (0)::numeric));
alter table public.colectivo_ventas add constraint colectivo_ventas_cantidad_check CHECK ((cantidad > 0));
alter table public.colectivo_ventas add constraint colectivo_ventas_estado_check CHECK ((estado = ANY (ARRAY['activa'::text, 'anulada'::text, 'bonificada'::text])));
alter table public.colectivo_ventas add constraint colectivo_ventas_precio_unitario_check CHECK ((precio_unitario >= (0)::numeric));
alter table public.colectivo_ventas add constraint colectivo_ventas_total_check CHECK ((total >= (0)::numeric));
alter table public.empresa_campanias add constraint empresa_campanias_cantidad_contratada_check CHECK ((cantidad_contratada >= 0));
alter table public.empresa_campanias add constraint empresa_campanias_estado_check CHECK ((estado = ANY (ARRAY['borrador'::text, 'pendiente_pago'::text, 'programada'::text, 'activa'::text, 'vencida'::text, 'finalizada'::text, 'cancelada'::text])));
alter table public.empresa_campanias add constraint empresa_campanias_estado_pago_check CHECK ((estado_pago = ANY (ARRAY['pendiente'::text, 'pagado'::text])));
alter table public.empresa_campanias add constraint empresa_campanias_iva_porcentaje_check CHECK ((iva_porcentaje >= (0)::numeric));
alter table public.empresa_campanias add constraint empresa_campanias_medio_pago_check CHECK ((medio_pago = ANY (ARRAY['efectivo'::text, 'mercadopago'::text, 'transferencia'::text])));
alter table public.empresa_campanias add constraint empresa_campanias_modalidad_check CHECK ((modalidad = ANY (ARRAY['unica'::text, 'mensual'::text])));
alter table public.empresa_campanias add constraint empresa_campanias_modalidad_comercial_chk CHECK (((modalidad_comercial IS NULL) OR (modalidad_comercial = ANY (ARRAY['legacy'::text, 'v2_10'::text]))));
alter table public.empresa_campanias add constraint empresa_campanias_precio_neto_check CHECK ((precio_neto >= (0)::numeric));
alter table public.empresa_campanias add constraint empresa_campanias_usos_por_codigo_check CHECK ((usos_por_codigo >= 1));
alter table public.empresa_codigo_usos add constraint empresa_codigo_usos_estado_check CHECK ((estado = ANY (ARRAY['consumido'::text, 'cancelado'::text])));
alter table public.empresa_codigos add constraint empresa_codigos_check CHECK ((usos_actuales <= usos_maximos));
alter table public.empresa_codigos add constraint empresa_codigos_estado_check CHECK ((estado = ANY (ARRAY['disponible'::text, 'utilizado'::text, 'vencido'::text, 'cancelado'::text, 'bloqueado'::text])));
alter table public.empresa_codigos add constraint empresa_codigos_usos_actuales_check CHECK ((usos_actuales >= 0));
alter table public.empresa_codigos add constraint empresa_codigos_usos_maximos_check CHECK ((usos_maximos >= 1));
alter table public.fin_categorias add constraint fin_categorias_ambito_check CHECK ((ambito = ANY (ARRAY['sim'::text, 'personal'::text, 'ambos'::text])));
alter table public.fin_categorias add constraint fin_categorias_tipo_check CHECK ((tipo = ANY (ARRAY['ingreso'::text, 'costo'::text, 'gasto'::text, 'inversion'::text, 'retiro'::text, 'ajuste'::text, 'sueldo_personal'::text])));
alter table public.fin_cierres_mensuales add constraint fin_cierres_mensuales_estado_check CHECK ((estado = ANY (ARRAY['abierto'::text, 'cerrado'::text, 'cerrado_con_diferencia'::text])));
alter table public.fin_cierres_mensuales add constraint fin_cierres_mensuales_mes_check CHECK ((mes ~ '^\d{4}-\d{2}$'::text));
alter table public.fin_comisiones_cobro add constraint fin_comisiones_cobro_acreditacion_check CHECK ((acreditacion = ANY (ARRAY['inmediata'::text, '24_hs'::text])));
alter table public.fin_comisiones_cobro add constraint fin_comisiones_cobro_iva_porcentaje_check CHECK ((iva_porcentaje >= (0)::numeric));
alter table public.fin_comisiones_cobro add constraint fin_comisiones_cobro_metodo_pago_check CHECK ((metodo_pago = ANY (ARRAY['qr'::text, 'debito'::text, 'credito'::text])));
alter table public.fin_comisiones_cobro add constraint fin_comisiones_cobro_porcentaje_base_check CHECK ((porcentaje_base >= (0)::numeric));
alter table public.fin_comisiones_cobro add constraint fin_comisiones_cobro_procesador_check CHECK ((procesador = ANY (ARRAY['mercado_pago'::text, 'payway'::text])));
alter table public.fin_configuracion add constraint fin_configuracion_id_check CHECK ((id = 1));
alter table public.fin_configuracion add constraint fin_configuracion_mes_inicio_check CHECK ((mes_inicio ~ '^\d{4}-\d{2}$'::text));
alter table public.fin_cuentas add constraint fin_cuentas_ambito_check CHECK ((ambito = ANY (ARRAY['sim'::text, 'personal'::text, 'compartida'::text])));
alter table public.fin_cuentas add constraint fin_cuentas_tipo_check CHECK ((tipo = ANY (ARRAY['efectivo'::text, 'mercado_pago'::text, 'banco'::text, 'otro'::text])));
alter table public.fin_deudas add constraint fin_deudas_cuenta_destino_check CHECK (((cuenta_destino IS NULL) OR (cuenta_destino = ANY (ARRAY['efectivo'::text, 'mercado_pago'::text]))));
alter table public.fin_deudas add constraint fin_deudas_cuotas_total_check CHECK (((cuotas_total >= 1) AND (cuotas_total <= 120)));
alter table public.fin_deudas add constraint fin_deudas_estado_check CHECK ((estado = ANY (ARRAY['activa'::text, 'pagada'::text, 'vencida'::text, 'cancelada'::text])));
alter table public.fin_deudas add constraint fin_deudas_monto_total_check CHECK ((monto_total > (0)::numeric));
alter table public.fin_eventos_futuros add constraint fin_eventos_futuros_cuenta_estimada_check CHECK ((cuenta_estimada = ANY (ARRAY['efectivo'::text, 'mercado_pago'::text])));
alter table public.fin_eventos_futuros add constraint fin_eventos_futuros_estado_check CHECK ((estado = ANY (ARRAY['pendiente'::text, 'cobrado'::text, 'pagado'::text, 'vencido'::text, 'cancelado'::text, 'estimado'::text])));
alter table public.fin_eventos_futuros add constraint fin_eventos_futuros_mes_contable_check CHECK ((mes_contable ~ '^\d{4}-\d{2}$'::text));
alter table public.fin_eventos_futuros add constraint fin_eventos_futuros_monto_check CHECK ((monto > (0)::numeric));
alter table public.fin_eventos_futuros add constraint fin_eventos_futuros_probabilidad_check CHECK (((probabilidad >= 0) AND (probabilidad <= 100)));
alter table public.fin_eventos_futuros add constraint fin_eventos_futuros_tipo_check CHECK ((tipo = ANY (ARRAY['cobro_futuro'::text, 'pago_futuro'::text, 'deuda'::text, 'cuota_deuda'::text, 'gasto_fijo'::text, 'ingreso_recurrente'::text, 'vencimiento'::text, 'compromiso_estimado'::text])));
alter table public.fin_excepciones_operativas add constraint fin_excepciones_operativas_horas_check CHECK (((horas IS NULL) OR ((horas >= (0)::numeric) AND (horas <= (24)::numeric))));
alter table public.fin_excepciones_operativas add constraint fin_excepciones_operativas_simuladores_check CHECK (((simuladores IS NULL) OR ((simuladores >= 0) AND (simuladores <= 50))));
alter table public.fin_movimientos add constraint fin_movimientos_ambito_check CHECK ((ambito = ANY (ARRAY['sim'::text, 'personal'::text])));
alter table public.fin_movimientos add constraint fin_movimientos_check CHECK (((tipo <> 'transferencia'::text) OR ((cuenta_origen_id IS NOT NULL) AND (cuenta_destino_id IS NOT NULL) AND (cuenta_origen_id <> cuenta_destino_id))));
alter table public.fin_movimientos add constraint fin_movimientos_check1 CHECK (((tipo <> ALL (ARRAY['ingreso'::text, 'egreso'::text])) OR (cuenta_origen_id IS NOT NULL)));
alter table public.fin_movimientos add constraint fin_movimientos_check2 CHECK (((tipo <> 'ajuste'::text) OR ((cuenta_origen_id IS NULL) <> (cuenta_destino_id IS NULL))));
alter table public.fin_movimientos add constraint fin_movimientos_clasificacion_check CHECK ((clasificacion = ANY (ARRAY['ingreso'::text, 'costo'::text, 'gasto'::text, 'inversion'::text, 'retiro'::text, 'ajuste'::text, 'otro'::text, 'sueldo_personal'::text, 'financiamiento'::text, 'pago_deuda'::text])));
alter table public.fin_movimientos add constraint fin_movimientos_mes_contable_check CHECK ((mes_contable ~ '^\d{4}-\d{2}$'::text));
alter table public.fin_movimientos add constraint fin_movimientos_monto_check CHECK ((monto > (0)::numeric));
alter table public.fin_movimientos add constraint fin_movimientos_origen_check CHECK ((origen = ANY (ARRAY['manual'::text, 'automatico'::text, 'ajuste'::text, 'transferencia'::text, 'ajuste_inicial'::text])));
alter table public.fin_movimientos add constraint fin_movimientos_tipo_check CHECK ((tipo = ANY (ARRAY['ingreso'::text, 'egreso'::text, 'transferencia'::text, 'ajuste'::text])));
alter table public.fin_recurrencias add constraint fin_recurrencias_cantidad_repeticiones_check CHECK (((cantidad_repeticiones IS NULL) OR ((cantidad_repeticiones >= 1) AND (cantidad_repeticiones <= 60))));
alter table public.fin_recurrencias add constraint fin_recurrencias_cuenta_estimada_check CHECK ((cuenta_estimada = ANY (ARRAY['efectivo'::text, 'mercado_pago'::text])));
alter table public.fin_recurrencias add constraint fin_recurrencias_frecuencia_check CHECK ((frecuencia = ANY (ARRAY['semanal'::text, 'mensual'::text, 'anual'::text])));
alter table public.fin_recurrencias add constraint fin_recurrencias_monto_check CHECK ((monto > (0)::numeric));
alter table public.fin_recurrencias add constraint fin_recurrencias_probabilidad_check CHECK (((probabilidad >= 0) AND (probabilidad <= 100)));
alter table public.fin_recurrencias add constraint fin_recurrencias_tipo_check CHECK ((tipo = ANY (ARRAY['cobro_futuro'::text, 'pago_futuro'::text, 'gasto_fijo'::text, 'ingreso_recurrente'::text, 'compromiso_estimado'::text, 'vencimiento'::text])));
alter table public.fin_reglas_clasificacion add constraint fin_reglas_clasificacion_ambito_check CHECK ((ambito = ANY (ARRAY['sim'::text, 'personal'::text])));
alter table public.fin_reglas_clasificacion add constraint fin_reglas_clasificacion_clasificacion_sugerida_check CHECK ((clasificacion_sugerida = ANY (ARRAY['ingreso'::text, 'costo'::text, 'gasto'::text, 'inversion'::text, 'retiro'::text, 'ajuste'::text, 'otro'::text])));
alter table public.fin_reglas_clasificacion add constraint fin_reglas_clasificacion_tipo_sugerido_check CHECK ((tipo_sugerido = ANY (ARRAY['ingreso'::text, 'egreso'::text, 'transferencia'::text, 'ajuste'::text])));
alter table public.fin_saldos_iniciales add constraint fin_saldos_iniciales_mes_check CHECK ((mes ~ '^\d{4}-\d{2}$'::text));
alter table public.fin_sueldos add constraint fin_sueldos_mes_check CHECK ((mes ~ '^\d{4}-\d{2}$'::text));
alter table public.fin_sueldos add constraint fin_sueldos_monto_check CHECK ((monto >= (0)::numeric));
alter table public.fin_whatsapp_pendientes add constraint fin_whatsapp_pendientes_estado_check CHECK ((estado = ANY (ARRAY['pendiente'::text, 'confirmado'::text, 'cancelado'::text, 'expirado'::text, 'guardado'::text, 'error'::text, 'no_entendido'::text])));
alter table public.gift_cards add constraint gift_cards_canal_chk CHECK ((canal = ANY (ARRAY['web'::text, 'admin'::text])));
alter table public.gift_cards add constraint gift_cards_canal_coherencia_chk CHECK (
CASE canal
    WHEN 'web'::text THEN ((medio_pago IS NULL) AND (procesador IS NULL) AND (registrado_por IS NULL))
    WHEN 'admin'::text THEN ((medio_pago IS NOT NULL) AND ((procesador IS NOT NULL) = (medio_pago = ANY (ARRAY['qr'::text, 'debito'::text, 'credito'::text]))) AND (mercado_pago_payment_id IS NULL) AND (mercado_pago_preference_id IS NULL))
    ELSE false
END);
alter table public.gift_cards add constraint gift_cards_estado_pago_check CHECK ((estado_pago = ANY (ARRAY['pendiente_pago'::text, 'pagado'::text, 'rechazado'::text, 'cancelado'::text])));
alter table public.gift_cards add constraint gift_cards_estado_uso_check CHECK ((estado_uso = ANY (ARRAY['pendiente'::text, 'lista'::text, 'usada'::text, 'vencida'::text, 'cancelada'::text])));
alter table public.gift_cards add constraint gift_cards_medio_pago_chk CHECK (((medio_pago IS NULL) OR (medio_pago = ANY (ARRAY['efectivo'::text, 'transferencia'::text, 'qr'::text, 'debito'::text, 'credito'::text]))));
alter table public.gift_cards add constraint gift_cards_modo_uso_check CHECK ((modo_uso = ANY (ARRAY['juntas'::text, 'separadas'::text])));
alter table public.gift_cards add constraint gift_cards_procesador_chk CHECK (((procesador IS NULL) OR (procesador = ANY (ARRAY['mercado_pago'::text, 'payway'::text]))));
alter table public.reserva_slots add constraint reserva_slots_ocupacion_chk CHECK (((ocupacion_min IS NULL) OR (((ocupacion_min >= 5) AND (ocupacion_min <= 720)) AND ((ocupacion_min % 5) = 0))));
alter table public.reservas add constraint reservas_cancelacion_chk CHECK (((cancelacion_resultado IS NULL) OR ((cancelacion_resultado = ANY (ARRAY['restituida'::text, 'sin_restitucion'::text])) AND (estado = 'cancelada'::text))));
alter table public.reservas add constraint reservas_mensualidad_chk CHECK (
CASE
    WHEN (origen = 'mensualidad'::text) THEN ((mensualidad_id IS NOT NULL) AND (duracion_minutos = ANY (ARRAY[10, 15, 20, 30, 45, 60])) AND (minutos_consumidos IS NOT NULL) AND (minutos_consumidos > 0) AND ((minutos_consumidos % 5) = 0) AND (condiciones_version IS NOT NULL) AND (condiciones_at IS NOT NULL) AND (referencia_publica IS NOT NULL) AND (((cobertura = 'saldo'::text) AND (total = (0)::numeric) AND (importe_complementario = (0)::numeric)) OR ((cobertura = 'mixta'::text) AND (importe_complementario > (0)::numeric) AND (total = importe_complementario))))
    ELSE ((mensualidad_id IS NULL) AND (minutos_consumidos IS NULL) AND (cobertura IS NULL) AND (importe_complementario = (0)::numeric))
END);
alter table public.reservas add constraint reservas_modalidad_chk CHECK (((modalidad IS NULL) OR (modalidad = ANY (ARRAY['legacy'::text, 'v2_10'::text]))));
alter table public.reservas add constraint reservas_referencia_chk CHECK (((referencia_publica IS NULL) OR (referencia_publica ~ '^RES-[ABCDEFGHJKLMNPQRSTUVWXYZ23456789]{4}-[ABCDEFGHJKLMNPQRSTUVWXYZ23456789]{4}$'::text)));
alter table public.reservas_precios_especiales add constraint al_menos_un_precio CHECK (((precio_10 IS NOT NULL) OR (precio_15 IS NOT NULL) OR (precio_20 IS NOT NULL) OR (precio_30 IS NOT NULL)));
alter table public.reservas_precios_especiales add constraint precio_10_no_negativo CHECK (((precio_10 IS NULL) OR (precio_10 >= 0)));
alter table public.reservas_precios_especiales add constraint precio_15_no_negativo CHECK (((precio_15 IS NULL) OR (precio_15 >= 0)));
alter table public.reservas_precios_especiales add constraint precio_20_no_negativo CHECK (((precio_20 IS NULL) OR (precio_20 >= 0)));
alter table public.reservas_precios_especiales add constraint precio_30_no_negativo CHECK (((precio_30 IS NULL) OR (precio_30 >= 0)));
alter table public.sorteos add constraint sorteos_estado_check CHECK ((estado = ANY (ARRAY['proximo'::text, 'activo'::text, 'finalizado'::text])));
alter table public.turnos_stand add constraint turnos_stand_modalidad_chk CHECK (((modalidad IS NULL) OR (modalidad = ANY (ARRAY['legacy'::text, 'v2_10'::text]))));

-- ── 5b. Índices ─────────────────────────────────────────────────────────────
-- Los seis ÚNICOS van primero: no son optimización, son reglas de negocio.
-- reserva_slots_activa_uq impide dos reservas activas en el mismo simulador, hora
-- y fecha; reservas_idem_uq y reservas_referencia_uq sostienen la idempotencia y
-- la referencia pública; campeonato_inscripciones_payment_uq impide cobrar dos
-- veces el mismo pago. Sin ellos varias suites pasarían por la razón equivocada.
CREATE UNIQUE INDEX IF NOT EXISTS campeonato_inscripciones_payment_uq ON public.campeonato_inscripciones USING btree (payment_id) WHERE (payment_id IS NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS campeonato_penalizaciones_uniq ON public.campeonato_penalizaciones USING btree (campeonato_id, fecha_origen_id, fecha_destino_id, categoria, piloto_key);
CREATE UNIQUE INDEX IF NOT EXISTS uq_empresa_uso_idempotency ON public.empresa_codigo_usos USING btree (idempotency_key) WHERE (idempotency_key IS NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS reserva_slots_activa_uq ON public.reserva_slots USING btree (fecha, hora, simulador) WHERE (estado = 'activa'::text);
CREATE UNIQUE INDEX IF NOT EXISTS reservas_idem_uq ON public.reservas USING btree (idempotency_key) WHERE (idempotency_key IS NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS reservas_referencia_uq ON public.reservas USING btree (referencia_publica) WHERE (referencia_publica IS NOT NULL);

CREATE INDEX IF NOT EXISTS idx_bloqueos_reservas_fecha_activo ON public.bloqueos_reservas USING btree (fecha, activo);
CREATE INDEX IF NOT EXISTS idx_bracket_cp_bracket ON public.campeonato_bracket_carrera_participantes USING btree (bracket_id);
CREATE INDEX IF NOT EXISTS idx_bracket_cp_carrera ON public.campeonato_bracket_carrera_participantes USING btree (carrera_id);
CREATE INDEX IF NOT EXISTS idx_bracket_cp_ronda ON public.campeonato_bracket_carrera_participantes USING btree (ronda_id);
CREATE INDEX IF NOT EXISTS idx_bracket_carreras_bracket ON public.campeonato_bracket_carreras USING btree (bracket_id);
CREATE INDEX IF NOT EXISTS idx_bracket_carreras_ronda ON public.campeonato_bracket_carreras USING btree (ronda_id);
CREATE INDEX IF NOT EXISTS idx_bracket_participantes_bracket ON public.campeonato_bracket_participantes USING btree (bracket_id);
CREATE INDEX IF NOT EXISTS idx_bracket_rondas_bracket ON public.campeonato_bracket_rondas USING btree (bracket_id);
CREATE INDEX IF NOT EXISTS idx_fechas_camp ON public.campeonato_fechas USING btree (campeonato_id);
CREATE INDEX IF NOT EXISTS campeonato_inscripciones_activas_idx ON public.campeonato_inscripciones USING btree (campeonato_id) WHERE (eliminada_at IS NULL);
CREATE INDEX IF NOT EXISTS idx_inscripciones_camp ON public.campeonato_inscripciones USING btree (campeonato_id);
CREATE INDEX IF NOT EXISTS idx_inscripciones_pago ON public.campeonato_inscripciones USING btree (estado_pago);
CREATE INDEX IF NOT EXISTS campeonato_registros_fecha_id_idx ON public.campeonato_registros USING btree (campeonato_fecha_id);
CREATE INDEX IF NOT EXISTS campeonato_registros_inscripcion_id_idx ON public.campeonato_registros USING btree (inscripcion_id);
CREATE INDEX IF NOT EXISTS campeonato_registros_oficial_idx ON public.campeonato_registros USING btree (campeonato_fecha_id, categoria, tiempo_oficial_ms);
CREATE INDEX IF NOT EXISTS idx_registros_campeonato ON public.campeonato_registros USING btree (campeonato_id);
CREATE INDEX IF NOT EXISTS idx_registros_categoria ON public.campeonato_registros USING btree (categoria);
CREATE INDEX IF NOT EXISTS idx_registros_estado ON public.campeonato_registros USING btree (estado);
CREATE INDEX IF NOT EXISTS idx_registros_nombre ON public.campeonato_registros USING btree (nombre_completo);
CREATE INDEX IF NOT EXISTS idx_registros_tiempo ON public.campeonato_registros USING btree (tiempo_segundos);
CREATE INDEX IF NOT EXISTS idx_campeonatos_activos ON public.campeonatos USING btree (created_at DESC) WHERE (deleted_at IS NULL);
CREATE INDEX IF NOT EXISTS idx_colectivo_turnos_evento ON public.colectivo_turnos USING btree (evento_id);
CREATE INDEX IF NOT EXISTS idx_colectivo_turnos_evento_fecha ON public.colectivo_turnos USING btree (evento_id, fecha);
CREATE INDEX IF NOT EXISTS idx_colectivo_ventas_evento ON public.colectivo_ventas USING btree (evento_id);
CREATE INDEX IF NOT EXISTS idx_colectivo_ventas_evento_fecha ON public.colectivo_ventas USING btree (evento_id, fecha);
CREATE INDEX IF NOT EXISTS idx_empresa_campanias_activas ON public.empresa_campanias USING btree (deleted_at) WHERE (deleted_at IS NULL);
CREATE INDEX IF NOT EXISTS idx_empresa_codigo_usos_campania ON public.empresa_codigo_usos USING btree (campania_id);
CREATE INDEX IF NOT EXISTS idx_empresa_codigo_usos_codigo ON public.empresa_codigo_usos USING btree (codigo_id);
CREATE INDEX IF NOT EXISTS idx_empresa_codigos_campania ON public.empresa_codigos USING btree (campania_id);
CREATE INDEX IF NOT EXISTS idx_fin_cierres_ctas_cierre ON public.fin_cierres_cuentas USING btree (cierre_id);
CREATE INDEX IF NOT EXISTS idx_fin_cierres_mes ON public.fin_cierres_mensuales USING btree (mes);
CREATE INDEX IF NOT EXISTS idx_fin_ev_deuda ON public.fin_eventos_futuros USING btree (deuda_id);
CREATE INDEX IF NOT EXISTS idx_fin_ev_estado ON public.fin_eventos_futuros USING btree (estado);
CREATE INDEX IF NOT EXISTS idx_fin_ev_fecha ON public.fin_eventos_futuros USING btree (fecha);
CREATE INDEX IF NOT EXISTS idx_fin_ev_mes ON public.fin_eventos_futuros USING btree (mes_contable);
CREATE INDEX IF NOT EXISTS idx_fin_ev_recurrencia ON public.fin_eventos_futuros USING btree (recurrencia_id);
CREATE INDEX IF NOT EXISTS idx_fin_ev_tipo ON public.fin_eventos_futuros USING btree (tipo);
CREATE INDEX IF NOT EXISTS idx_fin_excepciones_fecha ON public.fin_excepciones_operativas USING btree (fecha);
CREATE INDEX IF NOT EXISTS idx_fin_logs_entidad ON public.fin_logs USING btree (entidad, entidad_id);
CREATE INDEX IF NOT EXISTS idx_fin_mov_ambito ON public.fin_movimientos USING btree (ambito);
CREATE INDEX IF NOT EXISTS idx_fin_mov_categoria ON public.fin_movimientos USING btree (categoria_id);
CREATE INDEX IF NOT EXISTS idx_fin_mov_clasif ON public.fin_movimientos USING btree (clasificacion);
CREATE INDEX IF NOT EXISTS idx_fin_mov_cta_destino ON public.fin_movimientos USING btree (cuenta_destino_id);
CREATE INDEX IF NOT EXISTS idx_fin_mov_cta_origen ON public.fin_movimientos USING btree (cuenta_origen_id);
CREATE INDEX IF NOT EXISTS idx_fin_mov_fecha ON public.fin_movimientos USING btree (fecha);
CREATE INDEX IF NOT EXISTS idx_fin_mov_mes ON public.fin_movimientos USING btree (mes_contable);
CREATE INDEX IF NOT EXISTS idx_fin_mov_origen ON public.fin_movimientos USING btree (origen);
CREATE INDEX IF NOT EXISTS idx_fin_mov_tipo ON public.fin_movimientos USING btree (tipo);
CREATE INDEX IF NOT EXISTS idx_fin_reglas_keyword ON public.fin_reglas_clasificacion USING btree (keyword);
CREATE INDEX IF NOT EXISTS idx_fin_wa_message_id ON public.fin_whatsapp_pendientes USING btree (message_id);
CREATE INDEX IF NOT EXISTS idx_fin_wa_phone_estado ON public.fin_whatsapp_pendientes USING btree (phone, estado, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_gift_card_logs_card ON public.gift_card_logs USING btree (gift_card_id, created_at DESC);
CREATE INDEX IF NOT EXISTS gift_cards_canal_idx ON public.gift_cards USING btree (canal, fecha_pago DESC);
CREATE INDEX IF NOT EXISTS idx_gift_cards_activas ON public.gift_cards USING btree (created_at DESC) WHERE (deleted_at IS NULL);
CREATE INDEX IF NOT EXISTS idx_gift_cards_codigo_unico ON public.gift_cards USING btree (codigo_unico);
CREATE INDEX IF NOT EXISTS idx_gift_cards_created_at ON public.gift_cards USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_gift_cards_estado_pago ON public.gift_cards USING btree (estado_pago);
CREATE INDEX IF NOT EXISTS idx_gift_cards_estado_uso ON public.gift_cards USING btree (estado_uso);
CREATE INDEX IF NOT EXISTS idx_gift_cards_grupo_compra_id ON public.gift_cards USING btree (grupo_compra_id);
CREATE INDEX IF NOT EXISTS idx_pendientes_completado ON public.pendientes USING btree (completado);
CREATE INDEX IF NOT EXISTS idx_pendientes_created_at ON public.pendientes USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_pendientes_fecha_limite ON public.pendientes USING btree (fecha_limite);
CREATE INDEX IF NOT EXISTS reserva_slots_reserva_id_idx ON public.reserva_slots USING btree (reserva_id);
CREATE INDEX IF NOT EXISTS idx_reservas_empresa_campania ON public.reservas USING btree (empresa_campania_id) WHERE (empresa_campania_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS reservas_fecha_idx ON public.reservas USING btree (fecha);
CREATE INDEX IF NOT EXISTS reservas_mens_proximas_idx ON public.reservas USING btree (mensualidad_id, estado, fecha, hora) WHERE (mensualidad_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS reservas_mensualidad_idx ON public.reservas USING btree (mensualidad_id, fecha, hora) WHERE (mensualidad_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS reservas_precios_especiales_fecha_idx ON public.reservas_precios_especiales USING btree (fecha);
CREATE INDEX IF NOT EXISTS idx_sorteos_activos ON public.sorteos USING btree (created_at DESC) WHERE (deleted_at IS NULL);
CREATE INDEX IF NOT EXISTS turnos_stand_estado_idx ON public.turnos_stand USING btree (estado);
CREATE INDEX IF NOT EXISTS turnos_stand_fecha_hora_idx ON public.turnos_stand USING btree (fecha, hora);
CREATE INDEX IF NOT EXISTS turnos_stand_fecha_idx ON public.turnos_stand USING btree (fecha);

-- ── 4. Claves foráneas ──────────────────────────────────────────────────────
-- Nota: reservas.mensualidad_id apunta a mensualidades, que la crea
-- db/mensualidades-m2.sql. Por eso el esquema base se aplica ANTES de los
-- incrementales y esta FK se agrega al final, en 04b.
alter table public.campeonato_bracket add constraint campeonato_bracket_campeonato_id_fkey FOREIGN KEY (campeonato_id) REFERENCES campeonatos(id) ON DELETE CASCADE;
alter table public.campeonato_bracket_carrera_participantes add constraint campeonato_bracket_carrera_participantes_bracket_id_fkey FOREIGN KEY (bracket_id) REFERENCES campeonato_bracket(id) ON DELETE CASCADE;
alter table public.campeonato_bracket_carrera_participantes add constraint campeonato_bracket_carrera_participantes_carrera_id_fkey FOREIGN KEY (carrera_id) REFERENCES campeonato_bracket_carreras(id) ON DELETE CASCADE;
alter table public.campeonato_bracket_carrera_participantes add constraint campeonato_bracket_carrera_participantes_inscripcion_id_fkey FOREIGN KEY (inscripcion_id) REFERENCES campeonato_inscripciones(id) ON DELETE CASCADE;
alter table public.campeonato_bracket_carrera_participantes add constraint campeonato_bracket_carrera_participantes_origen_carrera_id_fkey FOREIGN KEY (origen_carrera_id) REFERENCES campeonato_bracket_carreras(id) ON DELETE SET NULL;
alter table public.campeonato_bracket_carrera_participantes add constraint campeonato_bracket_carrera_participantes_ronda_id_fkey FOREIGN KEY (ronda_id) REFERENCES campeonato_bracket_rondas(id) ON DELETE CASCADE;
alter table public.campeonato_bracket_carreras add constraint campeonato_bracket_carreras_bracket_id_fkey FOREIGN KEY (bracket_id) REFERENCES campeonato_bracket(id) ON DELETE CASCADE;
alter table public.campeonato_bracket_carreras add constraint campeonato_bracket_carreras_ronda_id_fkey FOREIGN KEY (ronda_id) REFERENCES campeonato_bracket_rondas(id) ON DELETE CASCADE;
alter table public.campeonato_bracket_participantes add constraint campeonato_bracket_participantes_bracket_id_fkey FOREIGN KEY (bracket_id) REFERENCES campeonato_bracket(id) ON DELETE CASCADE;
alter table public.campeonato_bracket_participantes add constraint campeonato_bracket_participantes_inscripcion_id_fkey FOREIGN KEY (inscripcion_id) REFERENCES campeonato_inscripciones(id) ON DELETE CASCADE;
alter table public.campeonato_bracket_rondas add constraint campeonato_bracket_rondas_bracket_id_fkey FOREIGN KEY (bracket_id) REFERENCES campeonato_bracket(id) ON DELETE CASCADE;
alter table public.campeonato_fechas add constraint campeonato_fechas_campeonato_id_fkey FOREIGN KEY (campeonato_id) REFERENCES campeonatos(id) ON DELETE CASCADE;
alter table public.campeonato_inscripciones add constraint campeonato_inscripciones_campeonato_id_fkey FOREIGN KEY (campeonato_id) REFERENCES campeonatos(id);
alter table public.campeonato_penalizaciones add constraint campeonato_penalizaciones_campeonato_id_fkey FOREIGN KEY (campeonato_id) REFERENCES campeonatos(id) ON DELETE CASCADE;
alter table public.campeonato_penalizaciones add constraint campeonato_penalizaciones_fecha_destino_id_fkey FOREIGN KEY (fecha_destino_id) REFERENCES campeonato_fechas(id) ON DELETE CASCADE;
alter table public.campeonato_penalizaciones add constraint campeonato_penalizaciones_fecha_origen_id_fkey FOREIGN KEY (fecha_origen_id) REFERENCES campeonato_fechas(id) ON DELETE CASCADE;
alter table public.campeonato_penalizaciones add constraint campeonato_penalizaciones_inscripcion_id_fkey FOREIGN KEY (inscripcion_id) REFERENCES campeonato_inscripciones(id) ON DELETE SET NULL;
alter table public.campeonato_registros add constraint campeonato_registros_campeonato_fecha_id_fkey FOREIGN KEY (campeonato_fecha_id) REFERENCES campeonato_fechas(id);
alter table public.campeonato_registros add constraint campeonato_registros_campeonato_id_fkey FOREIGN KEY (campeonato_id) REFERENCES campeonatos(id);
alter table public.campeonato_registros add constraint campeonato_registros_inscripcion_id_fkey FOREIGN KEY (inscripcion_id) REFERENCES campeonato_inscripciones(id) ON DELETE SET NULL;
alter table public.colectivo_turnos add constraint colectivo_turnos_evento_id_fkey FOREIGN KEY (evento_id) REFERENCES colectivo_eventos(id) ON DELETE CASCADE;
alter table public.colectivo_ventas add constraint colectivo_ventas_evento_id_fkey FOREIGN KEY (evento_id) REFERENCES colectivo_eventos(id) ON DELETE CASCADE;
alter table public.colectivo_ventas add constraint colectivo_ventas_producto_id_fkey FOREIGN KEY (producto_id) REFERENCES colectivo_productos(id);
alter table public.empresa_codigo_usos add constraint empresa_codigo_usos_campania_id_fkey FOREIGN KEY (campania_id) REFERENCES empresa_campanias(id) ON DELETE CASCADE;
alter table public.empresa_codigo_usos add constraint empresa_codigo_usos_codigo_id_fkey FOREIGN KEY (codigo_id) REFERENCES empresa_codigos(id) ON DELETE CASCADE;
alter table public.empresa_codigos add constraint empresa_codigos_campania_id_fkey FOREIGN KEY (campania_id) REFERENCES empresa_campanias(id) ON DELETE CASCADE;
alter table public.fin_cierres_cuentas add constraint fin_cierres_cuentas_cierre_id_fkey FOREIGN KEY (cierre_id) REFERENCES fin_cierres_mensuales(id) ON DELETE CASCADE;
alter table public.fin_cierres_cuentas add constraint fin_cierres_cuentas_cuenta_id_fkey FOREIGN KEY (cuenta_id) REFERENCES fin_cuentas(id);
alter table public.fin_clasificacion_ingresos add constraint fin_clasificacion_ingresos_categoria_id_fkey FOREIGN KEY (categoria_id) REFERENCES fin_categorias(id);
alter table public.fin_deudas add constraint fin_deudas_movimiento_financiamiento_id_fkey FOREIGN KEY (movimiento_financiamiento_id) REFERENCES fin_movimientos(id) ON DELETE SET NULL;
alter table public.fin_eventos_futuros add constraint fin_eventos_futuros_categoria_id_fkey FOREIGN KEY (categoria_id) REFERENCES fin_categorias(id);
alter table public.fin_eventos_futuros add constraint fin_eventos_futuros_deuda_id_fkey FOREIGN KEY (deuda_id) REFERENCES fin_deudas(id) ON DELETE CASCADE;
alter table public.fin_eventos_futuros add constraint fin_eventos_futuros_movimiento_id_fkey FOREIGN KEY (movimiento_id) REFERENCES fin_movimientos(id) ON DELETE SET NULL;
alter table public.fin_eventos_futuros add constraint fin_eventos_futuros_recurrencia_id_fkey FOREIGN KEY (recurrencia_id) REFERENCES fin_recurrencias(id) ON DELETE SET NULL;
alter table public.fin_movimientos add constraint fin_movimientos_categoria_id_fkey FOREIGN KEY (categoria_id) REFERENCES fin_categorias(id);
alter table public.fin_movimientos add constraint fin_movimientos_cuenta_destino_id_fkey FOREIGN KEY (cuenta_destino_id) REFERENCES fin_cuentas(id);
alter table public.fin_movimientos add constraint fin_movimientos_cuenta_origen_id_fkey FOREIGN KEY (cuenta_origen_id) REFERENCES fin_cuentas(id);
alter table public.fin_recurrencias add constraint fin_recurrencias_categoria_id_fkey FOREIGN KEY (categoria_id) REFERENCES fin_categorias(id);
alter table public.fin_reglas_clasificacion add constraint fin_reglas_clasificacion_categoria_id_fkey FOREIGN KEY (categoria_id) REFERENCES fin_categorias(id);
alter table public.fin_reglas_clasificacion add constraint fin_reglas_clasificacion_cuenta_id_fkey FOREIGN KEY (cuenta_id) REFERENCES fin_cuentas(id);
alter table public.gift_card_logs add constraint gift_card_logs_gift_card_id_fkey FOREIGN KEY (gift_card_id) REFERENCES gift_cards(id) ON DELETE CASCADE;
alter table public.reserva_operacion add constraint reserva_operacion_reserva_id_fkey FOREIGN KEY (reserva_id) REFERENCES reservas(id) ON DELETE CASCADE;
alter table public.reserva_slots add constraint reserva_slots_reserva_id_fkey FOREIGN KEY (reserva_id) REFERENCES reservas(id) ON DELETE CASCADE;
alter table public.reservas add constraint reservas_empresa_campania_id_fkey FOREIGN KEY (empresa_campania_id) REFERENCES empresa_campanias(id) ON DELETE SET NULL;
alter table public.reservas add constraint reservas_empresa_codigo_id_fkey FOREIGN KEY (empresa_codigo_id) REFERENCES empresa_codigos(id) ON DELETE SET NULL;
alter table public.usos_codigos_descuento add constraint usos_codigos_descuento_codigo_id_fkey FOREIGN KEY (codigo_id) REFERENCES codigos_descuento(id);
alter table public.usos_codigos_descuento add constraint usos_codigos_descuento_reserva_id_fkey FOREIGN KEY (reserva_id) REFERENCES reservas(id);

-- ── 5. Row level security ───────────────────────────────────────────────────
-- Las 47 tablas tienen RLS activo y CERO policies: deny-by-default. Solo el
-- service_role (que saltea RLS) puede leerlas o escribirlas, igual que en
-- Producción. Verificado por introspección: pg_policies devuelve 0 filas.
alter table public.bloqueos_reservas enable row level security;
alter table public.campeonato_bracket enable row level security;
alter table public.campeonato_bracket_carrera_participantes enable row level security;
alter table public.campeonato_bracket_carreras enable row level security;
alter table public.campeonato_bracket_participantes enable row level security;
alter table public.campeonato_bracket_rondas enable row level security;
alter table public.campeonato_fechas enable row level security;
alter table public.campeonato_inscripciones enable row level security;
alter table public.campeonato_penalizaciones enable row level security;
alter table public.campeonato_registros enable row level security;
alter table public.campeonatos enable row level security;
alter table public.codigos_descuento enable row level security;
alter table public.colectivo_eventos enable row level security;
alter table public.colectivo_productos enable row level security;
alter table public.colectivo_turnos enable row level security;
alter table public.colectivo_ventas enable row level security;
alter table public.empresa_campanias enable row level security;
alter table public.empresa_codigo_usos enable row level security;
alter table public.empresa_codigos enable row level security;
alter table public.fin_categorias enable row level security;
alter table public.fin_cierres_cuentas enable row level security;
alter table public.fin_cierres_mensuales enable row level security;
alter table public.fin_clasificacion_ingresos enable row level security;
alter table public.fin_comisiones_cobro enable row level security;
alter table public.fin_configuracion enable row level security;
alter table public.fin_cuentas enable row level security;
alter table public.fin_deudas enable row level security;
alter table public.fin_eventos_futuros enable row level security;
alter table public.fin_excepciones_operativas enable row level security;
alter table public.fin_logs enable row level security;
alter table public.fin_movimientos enable row level security;
alter table public.fin_recurrencias enable row level security;
alter table public.fin_reglas_clasificacion enable row level security;
alter table public.fin_saldos_iniciales enable row level security;
alter table public.fin_sueldos enable row level security;
alter table public.fin_whatsapp_pendientes enable row level security;
alter table public.gift_card_logs enable row level security;
alter table public.gift_cards enable row level security;
alter table public.pendientes enable row level security;
alter table public.reserva_operacion enable row level security;
alter table public.reserva_slots enable row level security;
alter table public.reservas enable row level security;
alter table public.reservas_precios_especiales enable row level security;
alter table public.sorteos enable row level security;
alter table public.turnos_historicos enable row level security;
alter table public.turnos_stand enable row level security;
alter table public.usos_codigos_descuento enable row level security;

-- ── 6. Funciones que existían solo en Producción ────────────────────────────
-- De las 83 funciones propias de Producción, 77 ya las crean los archivos
-- incrementales de db/. Estas 6 faltaban (dos de ellas son los constructores del
-- tipo range, que se obtienen al crear el tipo en 01_tipos).

CREATE OR REPLACE FUNCTION public.fin_set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.updated_at = now();
  return new;
end $function$;

CREATE OR REPLACE FUNCTION public.cancelar_reserva_empresa(p_reserva_id bigint, p_liberar_codigo boolean)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE v_res public.reservas%ROWTYPE;
BEGIN
  SELECT * INTO v_res FROM public.reservas WHERE id = p_reserva_id AND origen = 'empresa' FOR UPDATE;
  IF NOT FOUND THEN RETURN false; END IF;
  IF v_res.estado = 'cancelada' THEN RETURN true; END IF;
  UPDATE public.reserva_slots SET estado = 'cancelada' WHERE reserva_id = p_reserva_id;
  UPDATE public.reservas SET estado = 'cancelada' WHERE id = p_reserva_id;
  IF p_liberar_codigo AND v_res.empresa_codigo_id IS NOT NULL THEN
    UPDATE public.empresa_codigos
       SET usos_actuales = greatest(usos_actuales - 1, 0), estado = 'disponible', updated_at = now()
     WHERE id = v_res.empresa_codigo_id;
    UPDATE public.empresa_codigo_usos SET estado = 'cancelado' WHERE reserva_id = p_reserva_id;
  END IF;
  RETURN true;
END;
$function$;

CREATE OR REPLACE FUNCTION public.crear_bloqueo_reserva(p_fecha date, p_todo_el_dia boolean, p_hora_inicio text, p_hora_fin text, p_simulador text, p_motivo text)
 RETURNS SETOF bloqueos_reservas
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  PERFORM pg_advisory_xact_lock(hashtext('reserva-slot:' || p_fecha)::bigint);
  RETURN QUERY
    INSERT INTO public.bloqueos_reservas (fecha, todo_el_dia, hora_inicio, hora_fin, simulador, motivo, activo)
    VALUES (p_fecha, p_todo_el_dia, p_hora_inicio, p_hora_fin, p_simulador, p_motivo, true)
    RETURNING *;
END;
$function$;

CREATE OR REPLACE FUNCTION public.mensualidad_bloques_coherentes(p_hora text, p_duracion integer, p_slots text[])
 RETURNS boolean
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO 'public'
AS $function$
  select p_hora ~ '^\d{2}:\d{2}$'
     and p_duracion in (15, 30, 45, 60)
     and p_slots is not null
     and array_length(p_slots, 1) = p_duracion / 15
     and p_slots = (
       select array_agg(
         lpad((((split_part(p_hora, ':', 1)::int * 60 + split_part(p_hora, ':', 2)::int) + i * 20) / 60)::text, 2, '0')
         || ':' ||
         lpad((((split_part(p_hora, ':', 1)::int * 60 + split_part(p_hora, ':', 2)::int) + i * 20) % 60)::text, 2, '0')
         order by i)
       from generate_series(0, p_duracion / 15 - 1) as i
     );
$function$;

-- ── 7. Triggers de Finanzas y de reserva_slots ──────────────────────────────
-- Los de mensualidad_* los crea db/mensualidades-m2.sql y se aplican después.
drop trigger if exists trg_fin_categorias_updated on public.fin_categorias;
create trigger trg_fin_categorias_updated before update on public.fin_categorias for each row execute function fin_set_updated_at();
drop trigger if exists trg_fin_cierres_updated on public.fin_cierres_mensuales;
create trigger trg_fin_cierres_updated before update on public.fin_cierres_mensuales for each row execute function fin_set_updated_at();
drop trigger if exists trg_fin_clasif_ing_updated on public.fin_clasificacion_ingresos;
create trigger trg_fin_clasif_ing_updated before update on public.fin_clasificacion_ingresos for each row execute function fin_set_updated_at();
drop trigger if exists trg_fin_config_updated on public.fin_configuracion;
create trigger trg_fin_config_updated before update on public.fin_configuracion for each row execute function fin_set_updated_at();
drop trigger if exists trg_fin_cuentas_updated on public.fin_cuentas;
create trigger trg_fin_cuentas_updated before update on public.fin_cuentas for each row execute function fin_set_updated_at();
drop trigger if exists trg_fin_deudas_updated on public.fin_deudas;
create trigger trg_fin_deudas_updated before update on public.fin_deudas for each row execute function fin_set_updated_at();
drop trigger if exists trg_fin_eventos_updated on public.fin_eventos_futuros;
create trigger trg_fin_eventos_updated before update on public.fin_eventos_futuros for each row execute function fin_set_updated_at();
drop trigger if exists trg_fin_excep_updated on public.fin_excepciones_operativas;
create trigger trg_fin_excep_updated before update on public.fin_excepciones_operativas for each row execute function fin_set_updated_at();
drop trigger if exists trg_fin_movimientos_updated on public.fin_movimientos;
create trigger trg_fin_movimientos_updated before update on public.fin_movimientos for each row execute function fin_set_updated_at();
drop trigger if exists trg_fin_recurrencias_updated on public.fin_recurrencias;
create trigger trg_fin_recurrencias_updated before update on public.fin_recurrencias for each row execute function fin_set_updated_at();
drop trigger if exists trg_fin_reglas_updated on public.fin_reglas_clasificacion;
create trigger trg_fin_reglas_updated before update on public.fin_reglas_clasificacion for each row execute function fin_set_updated_at();
drop trigger if exists trg_fin_saldos_ini_updated on public.fin_saldos_iniciales;
create trigger trg_fin_saldos_ini_updated before update on public.fin_saldos_iniciales for each row execute function fin_set_updated_at();
drop trigger if exists trg_fin_sueldos_updated on public.fin_sueldos;
create trigger trg_fin_sueldos_updated before update on public.fin_sueldos for each row execute function fin_set_updated_at();
